spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/fs}
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
    hikari:
      initialization-fail-timeout: 5000
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
    livereload:
      enabled: false
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
    add-properties: false
  jmx:
    enabled: false
system:
  login:
    bypass: true