spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/fs}
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  devtools:
    restart:
      enabled: false
system:
  login:
    bypass: false