server:
  tomcat:
    background-processor-delay: 30
    threads:
      min-spare: 5
      max: 20
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/fs}
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
    hikari:
      initialization-fail-timeout: 5000
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
    livereload:
      enabled: false
  thymeleaf:
    cache: true
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    add-properties: false
  jmx:
    enabled: false
logging:
  level:
    com:
      zaxxer:
        hikari: WARN
    org:
      springframework:
        data: WARN
      apache:
        tomcat: WARN
        catalina: WARN
      hibernate: WARN
system:
  login:
    bypass: false
