spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:mysql://localhost:3306/fs        #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: root                              #username: flowiee
    password: root                              #password: 080100
    hikari:
      initialization-fail-timeout: 5000
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
system:
  login:
    bypass: true