package com.flowiee.pms.shared.enums;

public enum MasterObject {
    Master,
    Order,
    OrderDetail,
    Material,
    Product,
    ProductVariant,
    ProductAttribute,
    ProductCombo,
    Cart,
    Customer,
    CustomerContact,
    Supplier,
    VoucherInfo,
    VoucherTicket,
    Storage,
    TicketImport,
    TicketExport,
    LedgerReceipt,
    LedgerPayment,
    LedgerTransaction,
    Account,
    AccountRole,
    GroupAccount,
    SystemConfig,
    Category,
    FileStorage
}